[project]
name = "django"
version = "0.1.0"
description = ""
authors = [
    {name = "Dmitriy0709",email = "opt-alko1@mail.ru"}
]
requires-python = ">=3.12"
dependencies = [
    "django-rest-framework (>=0.1.0,<0.2.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
